Repository jemalloc/jemalloc, pull requests merged in 2018-04, with the labels that each got.

#1155 Fix a background_thread shutdown issue.
  src/background_thread.c
  test/unit/background_thread_enable.c
Labels: bug

#1157 Consolidate the two memory loads in rtree_szind_slab_read().
  include/jemalloc/internal/rtree.h
Labels: optimization

#1167 Silence a compiler warning.
  src/arena.c
Labels: portability

#1166 Fix a typo.
  ChangeLog
Labels: documentation

#1177 Avoid a printf format specifier warning.
  include/jemalloc/internal/emitter.h
Labels: portability

#1185 Remove an incorrect assertion.
  src/background_thread.c
Labels: bug
