Repository jemalloc/jemalloc, pull requests merged in 2019-11, with the labels that each got.

#1622 Build a general purpose thread event handler
  Makefile.in
  include/jemalloc/internal/prof_inlines_b.h
  include/jemalloc/internal/thread_event.h
  include/jemalloc/internal/tsd.h
  msvc/projects/vc2015/jemalloc/jemalloc.vcxproj
  msvc/projects/vc2015/jemalloc/jemalloc.vcxproj.filters
  msvc/projects/vc2017/jemalloc/jemalloc.vcxproj
  msvc/projects/vc2017/jemalloc/jemalloc.vcxproj.filters
  src/jemalloc.c
  src/prof.c
  src/thread_event.c
  test/unit/thread_event.c
  test/unit/thread_event.sh
Labels: feature, optimization

#1661 Add -Wimplicit-fallthrough checks if supported
  configure.ac
  include/jemalloc/internal/hash.h
  include/jemalloc/internal/jemalloc_internal_macros.h
  include/jemalloc/jemalloc_defs.h.in
  include/jemalloc/jemalloc_macros.h.in
  src/arena.c
  src/malloc_io.c
  src/tsd.c
Labels: refactor

#1666 Check for large size first in the uncommon case of malloc.
  src/jemalloc.c
Labels: optimization

#1682 Emphasize no modification through thread.allocatedp allowed.
  doc/jemalloc.xml.in
Labels: documentation

#1683 Fix bug in prof_realloc
  include/jemalloc/internal/prof_inlines_b.h
Labels: bug

#1672 Bail out early for muzzy decay.
  src/arena.c
Labels: optimization

#1686 Add branch hints to free_fastpath
  src/jemalloc.c
Labels: optimization

#1671 Reduce footprint of bin_t.
  include/jemalloc/internal/arena_externs.h
  include/jemalloc/internal/bin.h
  include/jemalloc/internal/bin_stats.h
  include/jemalloc/internal/ctl.h
  src/arena.c
  src/ctl.c
Labels: optimization

#1670 Refactor arena_bin_malloc_hard().
  src/arena.c
Labels: refactor
