Repository jemalloc/jemalloc, pull requests merged in 2019-04, with the labels that each got.

#1473 Update Changelog for 5.2.0.
  ChangeLog
Labels: documentation, release

#1470 Ensure page alignment on extent_alloc.
  src/extent.c
  src/extent_dss.c
  src/extent_mmap.c
Labels: bug

#1486 Add nonfull_slabs to bin_stats_t.
  doc/jemalloc.xml.in
  include/jemalloc/internal/bin.h
  include/jemalloc/internal/bin_stats.h
  src/arena.c
  src/ctl.c
  src/stats.c
  test/unit/stats.c
Labels: profiling
