Repository jemalloc/jemalloc, pull requests merged in 2019-01, with the labels that each got.

#1404 Add Cirrus-CI config for FreeBSD builds
  .cirrus.yml
Labels: testing

#1407 Remove --branch=${CIRRUS_BASE_BRANCH} in git clone command.
  .cirrus.yml
Labels: testing

#1302 Avoid potential issues on extent zero-out.
  include/jemalloc/internal/arena_inlines_b.h
  src/extent.c
Labels: bug

#1408 Cirrus versionless
  .cirrus.yml
Labels: testing

#1409 Avoid creating bg thds for huge arena lone.
  include/jemalloc/internal/arena_externs.h
  src/arena.c
  src/background_thread.c
  src/ctl.c
  src/jemalloc.c
Labels: optimization
