Repository jemalloc/jemalloc, pull requests merged in 2019-09, with the labels that each got.

#1617 Make cache_bin_sz_t unsigned.
  include/jemalloc/internal/cache_bin.h
  src/tcache.c
Labels: refactor

#1613 Workaround the stringop-overflow check false positives.
  test/include/test/test.h
  test/src/test.c
  test/unit/log.c
Labels: testing

#1624 Fix tcache bin stack alignment.
  src/tcache.c
Labels: bug

#1626 Add --with-lg-page=16 to CI.
  .travis.yml
  scripts/gen_run_tests.py
  scripts/gen_travis.py
Labels: testing

#1635 Fix je_ prefix issue in test
  msvc/test_threads/test_threads.cpp
Labels: testing
