Repository jemalloc/jemalloc, pull requests merged in 2021-08, with the labels that each got.

#2104 Add Cirrus CI testing matrix
  .cirrus.yml
Labels: testing

#2111 Fix warnings when compiled with clang
  configure.ac
Labels: portability

#2115 HPA: Correctly calculate retained pages
  include/jemalloc/internal/hpdata.h
Labels: bug
